version: '3'
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb:/data/db
    command: --wiredTigerCacheSizeGB 1.5
  api:
    image: amer1candocker/mytop-demo
    container_name: api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env
    links:
      - db
  front:
    image: amer1candocker/mytop-demo-front
    container_name: front
    ports:
      - '8089:8089'
    depends_on:
      - api

